package com.huaren.logistics.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huaren.logistics.bean.Customer;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CUSTOMER.
*/
public class CustomerDao extends AbstractDao<Customer, String> {

    public static final String TABLENAME = "CUSTOMER";

    /**
     * Properties of entity Customer.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CooperateId = new Property(0, String.class, "cooperateId", true, "COOPERATE_ID");
        public final static Property CooperateName = new Property(1, String.class, "cooperateName", false, "COOPERATE_NAME");
        public final static Property AddTime = new Property(2, java.util.Date.class, "addTime", false, "ADD_TIME");
        public final static Property EditTime = new Property(3, java.util.Date.class, "editTime", false, "EDIT_TIME");
    };


    public CustomerDao(DaoConfig config) {
        super(config);
    }
    
    public CustomerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CUSTOMER' (" + //
                "'COOPERATE_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: cooperateId
                "'COOPERATE_NAME' TEXT NOT NULL ," + // 1: cooperateName
                "'ADD_TIME' INTEGER NOT NULL ," + // 2: addTime
                "'EDIT_TIME' INTEGER);"); // 3: editTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CUSTOMER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Customer entity) {
        stmt.clearBindings();
 
        String cooperateId = entity.getCooperateId();
        if (cooperateId != null) {
            stmt.bindString(1, cooperateId);
        }
        stmt.bindString(2, entity.getCooperateName());
        stmt.bindLong(3, entity.getAddTime().getTime());
 
        java.util.Date editTime = entity.getEditTime();
        if (editTime != null) {
            stmt.bindLong(4, editTime.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Customer readEntity(Cursor cursor, int offset) {
        Customer entity = new Customer( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // cooperateId
            cursor.getString(offset + 1), // cooperateName
            new java.util.Date(cursor.getLong(offset + 2)), // addTime
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)) // editTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Customer entity, int offset) {
        entity.setCooperateId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCooperateName(cursor.getString(offset + 1));
        entity.setAddTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setEditTime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Customer entity, long rowId) {
        return entity.getCooperateId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Customer entity) {
        if(entity != null) {
            return entity.getCooperateId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
