package com.huaren.logistics.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huaren.logistics.bean.DownBatchInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DOWN_BATCH_INFO.
*/
public class DownBatchInfoDao extends AbstractDao<DownBatchInfo, Long> {

    public static final String TABLENAME = "DOWN_BATCH_INFO";

    /**
     * Properties of entity DownBatchInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LPdtgBatch = new Property(1, long.class, "lPdtgBatch", false, "L_PDTG_BATCH");
        public final static Property AddTime = new Property(2, java.util.Date.class, "addTime", false, "ADD_TIME");
        public final static Property UserName = new Property(3, String.class, "userName", false, "USER_NAME");
    };


    public DownBatchInfoDao(DaoConfig config) {
        super(config);
    }
    
    public DownBatchInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DOWN_BATCH_INFO' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'L_PDTG_BATCH' INTEGER NOT NULL ," + // 1: lPdtgBatch
                "'ADD_TIME' INTEGER NOT NULL ," + // 2: addTime
                "'USER_NAME' TEXT NOT NULL );"); // 3: userName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DOWN_BATCH_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DownBatchInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLPdtgBatch());
        stmt.bindLong(3, entity.getAddTime().getTime());
        stmt.bindString(4, entity.getUserName());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DownBatchInfo readEntity(Cursor cursor, int offset) {
        DownBatchInfo entity = new DownBatchInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // lPdtgBatch
            new java.util.Date(cursor.getLong(offset + 2)), // addTime
            cursor.getString(offset + 3) // userName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DownBatchInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLPdtgBatch(cursor.getLong(offset + 1));
        entity.setAddTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setUserName(cursor.getString(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DownBatchInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DownBatchInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
