package com.huaren.logistics.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huaren.logistics.bean.RecycleScan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RECYCLE_SCAN.
*/
public class RecycleScanDao extends AbstractDao<RecycleScan, Long> {

    public static final String TABLENAME = "RECYCLE_SCAN";

    /**
     * Properties of entity RecycleScan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LPdtgBatch = new Property(1, int.class, "lPdtgBatch", false, "L_PDTG_BATCH");
        public final static Property RecycleScanTime = new Property(2, java.util.Date.class, "recycleScanTime", false, "RECYCLE_SCAN_TIME");
        public final static Property ScanCode = new Property(3, String.class, "scanCode", false, "SCAN_CODE");
        public final static Property Status = new Property(4, String.class, "status", false, "STATUS");
        public final static Property EditTime = new Property(5, java.util.Date.class, "editTime", false, "EDIT_TIME");
        public final static Property UserName = new Property(6, String.class, "userName", false, "USER_NAME");
        public final static Property RecycleType = new Property(7, long.class, "recycleType", false, "RECYCLE_TYPE");
        public final static Property RecycleTypeValue = new Property(8, String.class, "recycleTypeValue", false, "RECYCLE_TYPE_VALUE");
    };


    public RecycleScanDao(DaoConfig config) {
        super(config);
    }
    
    public RecycleScanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RECYCLE_SCAN' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'L_PDTG_BATCH' INTEGER NOT NULL ," + // 1: lPdtgBatch
                "'RECYCLE_SCAN_TIME' INTEGER NOT NULL ," + // 2: recycleScanTime
                "'SCAN_CODE' TEXT NOT NULL ," + // 3: scanCode
                "'STATUS' TEXT NOT NULL ," + // 4: status
                "'EDIT_TIME' INTEGER," + // 5: editTime
                "'USER_NAME' TEXT NOT NULL ," + // 6: userName
                "'RECYCLE_TYPE' INTEGER NOT NULL ," + // 7: recycleType
                "'RECYCLE_TYPE_VALUE' TEXT NOT NULL );"); // 8: recycleTypeValue
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RECYCLE_SCAN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecycleScan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getLPdtgBatch());
        stmt.bindLong(3, entity.getRecycleScanTime().getTime());
        stmt.bindString(4, entity.getScanCode());
        stmt.bindString(5, entity.getStatus());
 
        java.util.Date editTime = entity.getEditTime();
        if (editTime != null) {
            stmt.bindLong(6, editTime.getTime());
        }
        stmt.bindString(7, entity.getUserName());
        stmt.bindLong(8, entity.getRecycleType());
        stmt.bindString(9, entity.getRecycleTypeValue());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RecycleScan readEntity(Cursor cursor, int offset) {
        RecycleScan entity = new RecycleScan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // lPdtgBatch
            new java.util.Date(cursor.getLong(offset + 2)), // recycleScanTime
            cursor.getString(offset + 3), // scanCode
            cursor.getString(offset + 4), // status
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)), // editTime
            cursor.getString(offset + 6), // userName
            cursor.getLong(offset + 7), // recycleType
            cursor.getString(offset + 8) // recycleTypeValue
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RecycleScan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLPdtgBatch(cursor.getInt(offset + 1));
        entity.setRecycleScanTime(new java.util.Date(cursor.getLong(offset + 2)));
        entity.setScanCode(cursor.getString(offset + 3));
        entity.setStatus(cursor.getString(offset + 4));
        entity.setEditTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
        entity.setUserName(cursor.getString(offset + 6));
        entity.setRecycleType(cursor.getLong(offset + 7));
        entity.setRecycleTypeValue(cursor.getString(offset + 8));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RecycleScan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RecycleScan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
