package com.huaren.logistics.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huaren.logistics.bean.RecycleInput;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RECYCLE_INPUT.
*/
public class RecycleInputDao extends AbstractDao<RecycleInput, Long> {

    public static final String TABLENAME = "RECYCLE_INPUT";

    /**
     * Properties of entity RecycleInput.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderBatchId = new Property(1, String.class, "orderBatchId", false, "ORDER_BATCH_ID");
        public final static Property CooperateId = new Property(2, String.class, "cooperateId", false, "COOPERATE_ID");
        public final static Property LPdtgBatch = new Property(3, int.class, "lPdtgBatch", false, "L_PDTG_BATCH");
        public final static Property DriversID = new Property(4, String.class, "driversID", false, "DRIVERS_ID");
        public final static Property RecycleNum = new Property(5, int.class, "recycleNum", false, "RECYCLE_NUM");
        public final static Property RecycleType = new Property(6, long.class, "recycleType", false, "RECYCLE_TYPE");
        public final static Property RecycleTypeValue = new Property(7, String.class, "recycleTypeValue", false, "RECYCLE_TYPE_VALUE");
        public final static Property Status = new Property(8, String.class, "status", false, "STATUS");
        public final static Property RecycleTime = new Property(9, java.util.Date.class, "recycleTime", false, "RECYCLE_TIME");
        public final static Property EditTime = new Property(10, java.util.Date.class, "editTime", false, "EDIT_TIME");
        public final static Property UserName = new Property(11, String.class, "userName", false, "USER_NAME");
    };


    public RecycleInputDao(DaoConfig config) {
        super(config);
    }
    
    public RecycleInputDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RECYCLE_INPUT' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ORDER_BATCH_ID' TEXT NOT NULL ," + // 1: orderBatchId
                "'COOPERATE_ID' TEXT NOT NULL ," + // 2: cooperateId
                "'L_PDTG_BATCH' INTEGER NOT NULL ," + // 3: lPdtgBatch
                "'DRIVERS_ID' TEXT NOT NULL ," + // 4: driversID
                "'RECYCLE_NUM' INTEGER NOT NULL ," + // 5: recycleNum
                "'RECYCLE_TYPE' INTEGER NOT NULL ," + // 6: recycleType
                "'RECYCLE_TYPE_VALUE' TEXT NOT NULL ," + // 7: recycleTypeValue
                "'STATUS' TEXT NOT NULL ," + // 8: status
                "'RECYCLE_TIME' INTEGER NOT NULL ," + // 9: recycleTime
                "'EDIT_TIME' INTEGER," + // 10: editTime
                "'USER_NAME' TEXT NOT NULL );"); // 11: userName
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RECYCLE_INPUT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecycleInput entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getOrderBatchId());
        stmt.bindString(3, entity.getCooperateId());
        stmt.bindLong(4, entity.getLPdtgBatch());
        stmt.bindString(5, entity.getDriversID());
        stmt.bindLong(6, entity.getRecycleNum());
        stmt.bindLong(7, entity.getRecycleType());
        stmt.bindString(8, entity.getRecycleTypeValue());
        stmt.bindString(9, entity.getStatus());
        stmt.bindLong(10, entity.getRecycleTime().getTime());
 
        java.util.Date editTime = entity.getEditTime();
        if (editTime != null) {
            stmt.bindLong(11, editTime.getTime());
        }
        stmt.bindString(12, entity.getUserName());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RecycleInput readEntity(Cursor cursor, int offset) {
        RecycleInput entity = new RecycleInput( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // orderBatchId
            cursor.getString(offset + 2), // cooperateId
            cursor.getInt(offset + 3), // lPdtgBatch
            cursor.getString(offset + 4), // driversID
            cursor.getInt(offset + 5), // recycleNum
            cursor.getLong(offset + 6), // recycleType
            cursor.getString(offset + 7), // recycleTypeValue
            cursor.getString(offset + 8), // status
            new java.util.Date(cursor.getLong(offset + 9)), // recycleTime
            cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)), // editTime
            cursor.getString(offset + 11) // userName
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RecycleInput entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderBatchId(cursor.getString(offset + 1));
        entity.setCooperateId(cursor.getString(offset + 2));
        entity.setLPdtgBatch(cursor.getInt(offset + 3));
        entity.setDriversID(cursor.getString(offset + 4));
        entity.setRecycleNum(cursor.getInt(offset + 5));
        entity.setRecycleType(cursor.getLong(offset + 6));
        entity.setRecycleTypeValue(cursor.getString(offset + 7));
        entity.setStatus(cursor.getString(offset + 8));
        entity.setRecycleTime(new java.util.Date(cursor.getLong(offset + 9)));
        entity.setEditTime(cursor.isNull(offset + 10) ? null : new java.util.Date(cursor.getLong(offset + 10)));
        entity.setUserName(cursor.getString(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RecycleInput entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RecycleInput entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
