package com.huaren.logistics.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.huaren.logistics.bean.RecycleScan;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RECYCLE_SCAN.
*/
public class RecycleScanDao extends AbstractDao<RecycleScan, Long> {

    public static final String TABLENAME = "RECYCLE_SCAN";

    /**
     * Properties of entity RecycleScan.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property RecycleScanTime = new Property(1, java.util.Date.class, "recycleScanTime", false, "RECYCLE_SCAN_TIME");
        public final static Property ScanCode = new Property(2, String.class, "scanCode", false, "SCAN_CODE");
        public final static Property EditTime = new Property(3, java.util.Date.class, "editTime", false, "EDIT_TIME");
    };


    public RecycleScanDao(DaoConfig config) {
        super(config);
    }
    
    public RecycleScanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'RECYCLE_SCAN' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'RECYCLE_SCAN_TIME' INTEGER NOT NULL ," + // 1: recycleScanTime
                "'SCAN_CODE' TEXT NOT NULL ," + // 2: scanCode
                "'EDIT_TIME' INTEGER);"); // 3: editTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RECYCLE_SCAN'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, RecycleScan entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getRecycleScanTime().getTime());
        stmt.bindString(3, entity.getScanCode());
 
        java.util.Date editTime = entity.getEditTime();
        if (editTime != null) {
            stmt.bindLong(4, editTime.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public RecycleScan readEntity(Cursor cursor, int offset) {
        RecycleScan entity = new RecycleScan( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            new java.util.Date(cursor.getLong(offset + 1)), // recycleScanTime
            cursor.getString(offset + 2), // scanCode
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)) // editTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, RecycleScan entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setRecycleScanTime(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setScanCode(cursor.getString(offset + 2));
        entity.setEditTime(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RecycleScan entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RecycleScan entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
