package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUSTOMER.
 */
public class Customer implements java.io.Serializable {

    private String id;
    /** Not-null value. */
    private String cooperateId;
    private int lPdtgBatch;
    /** Not-null value. */
    private String sPdtgCustfullname;
    /** Not-null value. */
    private String coopPwd;
    /** Not-null value. */
    private String status;
    /** Not-null value. */
    private java.util.Date addTime;
    private java.util.Date editTime;
    /** Not-null value. */
    private String userName;

    public Customer() {
    }

    public Customer(String id) {
        this.id = id;
    }

    public Customer(String id, String cooperateId, int lPdtgBatch, String sPdtgCustfullname, String coopPwd, String status, java.util.Date addTime, java.util.Date editTime, String userName) {
        this.id = id;
        this.cooperateId = cooperateId;
        this.lPdtgBatch = lPdtgBatch;
        this.sPdtgCustfullname = sPdtgCustfullname;
        this.coopPwd = coopPwd;
        this.status = status;
        this.addTime = addTime;
        this.editTime = editTime;
        this.userName = userName;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCooperateId() {
        return cooperateId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCooperateId(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    public int getLPdtgBatch() {
        return lPdtgBatch;
    }

    public void setLPdtgBatch(int lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public String getSPdtgCustfullname() {
        return sPdtgCustfullname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSPdtgCustfullname(String sPdtgCustfullname) {
        this.sPdtgCustfullname = sPdtgCustfullname;
    }

    /** Not-null value. */
    public String getCoopPwd() {
        return coopPwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCoopPwd(String coopPwd) {
        this.coopPwd = coopPwd;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

}
