package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUSTOMER.
 */
public class Customer implements java.io.Serializable {

    private String cooperateId;
    /** Not-null value. */
    private String sPdtgCustfullname;
    /** Not-null value. */
    private String coopPwd;
    /** Not-null value. */
    private java.util.Date addTime;
    private java.util.Date editTime;

    public Customer() {
    }

    public Customer(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    public Customer(String cooperateId, String sPdtgCustfullname, String coopPwd, java.util.Date addTime, java.util.Date editTime) {
        this.cooperateId = cooperateId;
        this.sPdtgCustfullname = sPdtgCustfullname;
        this.coopPwd = coopPwd;
        this.addTime = addTime;
        this.editTime = editTime;
    }

    public String getCooperateId() {
        return cooperateId;
    }

    public void setCooperateId(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    /** Not-null value. */
    public String getSPdtgCustfullname() {
        return sPdtgCustfullname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSPdtgCustfullname(String sPdtgCustfullname) {
        this.sPdtgCustfullname = sPdtgCustfullname;
    }

    /** Not-null value. */
    public String getCoopPwd() {
        return coopPwd;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCoopPwd(String coopPwd) {
        this.coopPwd = coopPwd;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
