package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CUSTOMER.
 */
public class Customer implements java.io.Serializable {

    private String cooperateId;
    /** Not-null value. */
    private String cooperateName;
    /** Not-null value. */
    private java.util.Date addTime;
    private java.util.Date editTime;

    public Customer() {
    }

    public Customer(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    public Customer(String cooperateId, String cooperateName, java.util.Date addTime, java.util.Date editTime) {
        this.cooperateId = cooperateId;
        this.cooperateName = cooperateName;
        this.addTime = addTime;
        this.editTime = editTime;
    }

    public String getCooperateId() {
        return cooperateId;
    }

    public void setCooperateId(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    /** Not-null value. */
    public String getCooperateName() {
        return cooperateName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCooperateName(String cooperateName) {
        this.cooperateName = cooperateName;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
