package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWN_BATCH_INFO.
 */
public class DownBatchInfo implements java.io.Serializable {

    private Long id;
    private long lPdtgBatch;
    /** Not-null value. */
    private java.util.Date addTime;
    /** Not-null value. */
    private String userName;

    public DownBatchInfo() {
    }

    public DownBatchInfo(Long id) {
        this.id = id;
    }

    public DownBatchInfo(Long id, long lPdtgBatch, java.util.Date addTime, String userName) {
        this.id = id;
        this.lPdtgBatch = lPdtgBatch;
        this.addTime = addTime;
        this.userName = userName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getLPdtgBatch() {
        return lPdtgBatch;
    }

    public void setLPdtgBatch(long lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

}
