package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWN_BATCH_INFO.
 */
public class DownBatchInfo implements java.io.Serializable {

    private Long lPdtgBatch;
    /** Not-null value. */
    private java.util.Date addTime;

    public DownBatchInfo() {
    }

    public DownBatchInfo(Long lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    public DownBatchInfo(Long lPdtgBatch, java.util.Date addTime) {
        this.lPdtgBatch = lPdtgBatch;
        this.addTime = addTime;
    }

    public Long getLPdtgBatch() {
        return lPdtgBatch;
    }

    public void setLPdtgBatch(Long lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

}
