package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOGISTICS_ORDER.
 */
public class LogisticsOrder implements java.io.Serializable {

    private String ordered;
    /** Not-null value. */
    private String dispatchNumber;
    /** Not-null value. */
    private String dPdtgDate;
    /** Not-null value. */
    private String lPdtgBatch;
    /** Not-null value. */
    private String lPdtgMerdcategOldkey;
    private int boxNumber;
    /** Not-null value. */
    private String pathName;
    /** Not-null value. */
    private String orderStatus;
    private String evaluation;
    /** Not-null value. */
    private String cooperateID;
    /** Not-null value. */
    private java.util.Date addTime;
    private java.util.Date editTime;

    public LogisticsOrder() {
    }

    public LogisticsOrder(String ordered) {
        this.ordered = ordered;
    }

    public LogisticsOrder(String ordered, String dispatchNumber, String dPdtgDate, String lPdtgBatch, String lPdtgMerdcategOldkey, int boxNumber, String pathName, String orderStatus, String evaluation, String cooperateID, java.util.Date addTime, java.util.Date editTime) {
        this.ordered = ordered;
        this.dispatchNumber = dispatchNumber;
        this.dPdtgDate = dPdtgDate;
        this.lPdtgBatch = lPdtgBatch;
        this.lPdtgMerdcategOldkey = lPdtgMerdcategOldkey;
        this.boxNumber = boxNumber;
        this.pathName = pathName;
        this.orderStatus = orderStatus;
        this.evaluation = evaluation;
        this.cooperateID = cooperateID;
        this.addTime = addTime;
        this.editTime = editTime;
    }

    public String getOrdered() {
        return ordered;
    }

    public void setOrdered(String ordered) {
        this.ordered = ordered;
    }

    /** Not-null value. */
    public String getDispatchNumber() {
        return dispatchNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDispatchNumber(String dispatchNumber) {
        this.dispatchNumber = dispatchNumber;
    }

    /** Not-null value. */
    public String getDPdtgDate() {
        return dPdtgDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDPdtgDate(String dPdtgDate) {
        this.dPdtgDate = dPdtgDate;
    }

    /** Not-null value. */
    public String getLPdtgBatch() {
        return lPdtgBatch;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLPdtgBatch(String lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public String getLPdtgMerdcategOldkey() {
        return lPdtgMerdcategOldkey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLPdtgMerdcategOldkey(String lPdtgMerdcategOldkey) {
        this.lPdtgMerdcategOldkey = lPdtgMerdcategOldkey;
    }

    public int getBoxNumber() {
        return boxNumber;
    }

    public void setBoxNumber(int boxNumber) {
        this.boxNumber = boxNumber;
    }

    /** Not-null value. */
    public String getPathName() {
        return pathName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPathName(String pathName) {
        this.pathName = pathName;
    }

    /** Not-null value. */
    public String getOrderStatus() {
        return orderStatus;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getEvaluation() {
        return evaluation;
    }

    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    /** Not-null value. */
    public String getCooperateID() {
        return cooperateID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCooperateID(String cooperateID) {
        this.cooperateID = cooperateID;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
