package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDER_DETAIL.
 */
public class OrderDetail implements java.io.Serializable {

    /** Not-null value. */
    private String goodsId;
    /** Not-null value. */
    private String ordered;
    /** Not-null value. */
    private String goodsName;
    /** Not-null value. */
    private String dispatchType;
    /** Not-null value. */
    private String iGroiValunum;
    private String lpn;
    /** Not-null value. */
    private String detailStatus;
    /** Not-null value. */
    private java.util.Date addTime;
    private java.util.Date editTime;

    public OrderDetail() {
    }

    public OrderDetail(String lpn) {
        this.lpn = lpn;
    }

    public OrderDetail(String goodsId, String ordered, String goodsName, String dispatchType, String iGroiValunum, String lpn, String detailStatus, java.util.Date addTime, java.util.Date editTime) {
        this.goodsId = goodsId;
        this.ordered = ordered;
        this.goodsName = goodsName;
        this.dispatchType = dispatchType;
        this.iGroiValunum = iGroiValunum;
        this.lpn = lpn;
        this.detailStatus = detailStatus;
        this.addTime = addTime;
        this.editTime = editTime;
    }

    /** Not-null value. */
    public String getGoodsId() {
        return goodsId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoodsId(String goodsId) {
        this.goodsId = goodsId;
    }

    /** Not-null value. */
    public String getOrdered() {
        return ordered;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrdered(String ordered) {
        this.ordered = ordered;
    }

    /** Not-null value. */
    public String getGoodsName() {
        return goodsName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    /** Not-null value. */
    public String getDispatchType() {
        return dispatchType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDispatchType(String dispatchType) {
        this.dispatchType = dispatchType;
    }

    /** Not-null value. */
    public String getIGroiValunum() {
        return iGroiValunum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setIGroiValunum(String iGroiValunum) {
        this.iGroiValunum = iGroiValunum;
    }

    public String getLpn() {
        return lpn;
    }

    public void setLpn(String lpn) {
        this.lpn = lpn;
    }

    /** Not-null value. */
    public String getDetailStatus() {
        return detailStatus;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDetailStatus(String detailStatus) {
        this.detailStatus = detailStatus;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
