package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDER_BATCH.
 */
public class OrderBatch implements java.io.Serializable {

    private String id;
    /** Not-null value. */
    private String cooperateId;
    private String sPdtgCustfullname;
    private int lPdtgBatch;
    /** Not-null value. */
    private String driversID;
    private String evaluation;
    private String canEvalutaion;
    /** Not-null value. */
    private String status;
    /** Not-null value. */
    private java.util.Date addTime;
    private java.util.Date editTime;

    public OrderBatch() {
    }

    public OrderBatch(String id) {
        this.id = id;
    }

    public OrderBatch(String id, String cooperateId, String sPdtgCustfullname, int lPdtgBatch, String driversID, String evaluation, String canEvalutaion, String status, java.util.Date addTime, java.util.Date editTime) {
        this.id = id;
        this.cooperateId = cooperateId;
        this.sPdtgCustfullname = sPdtgCustfullname;
        this.lPdtgBatch = lPdtgBatch;
        this.driversID = driversID;
        this.evaluation = evaluation;
        this.canEvalutaion = canEvalutaion;
        this.status = status;
        this.addTime = addTime;
        this.editTime = editTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCooperateId() {
        return cooperateId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCooperateId(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    public String getSPdtgCustfullname() {
        return sPdtgCustfullname;
    }

    public void setSPdtgCustfullname(String sPdtgCustfullname) {
        this.sPdtgCustfullname = sPdtgCustfullname;
    }

    public int getLPdtgBatch() {
        return lPdtgBatch;
    }

    public void setLPdtgBatch(int lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public String getDriversID() {
        return driversID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDriversID(String driversID) {
        this.driversID = driversID;
    }

    public String getEvaluation() {
        return evaluation;
    }

    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }

    public String getCanEvalutaion() {
        return canEvalutaion;
    }

    public void setCanEvalutaion(String canEvalutaion) {
        this.canEvalutaion = canEvalutaion;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
