package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ORDER_DETAIL.
 */
public class OrderDetail implements java.io.Serializable {

    private String detailId;
    /** Not-null value. */
    private String customerId;
    /** Not-null value. */
    private String cooperateId;
    /** Not-null value. */
    private String dispatchNumber;
    /** Not-null value. */
    private String dispatchCreatTime;
    /** Not-null value. */
    private String driversID;
    /** Not-null value. */
    private String sPdtgEmplname;
    /** Not-null value. */
    private String sPdtgEmplname2;
    /** Not-null value. */
    private String suicherenyuanID;
    /** Not-null value. */
    private String suicherenyuanID2;
    /** Not-null value. */
    private String sPdtgEmplname3;
    /** Not-null value. */
    private String sPdtgVehicleno;
    /** Not-null value. */
    private String countPieces;
    private int lPdtgBatch;
    /** Not-null value. */
    private String ordered;
    /** Not-null value. */
    private String orderId;
    /** Not-null value. */
    private String waveKey;
    /** Not-null value. */
    private String lpn;
    /** Not-null value. */
    private String mtype;
    /** Not-null value. */
    private String uom;
    /** Not-null value. */
    private String detailStatus;
    /** Not-null value. */
    private String status;
    /** Not-null value. */
    private java.util.Date addTime;
    private java.util.Date editTime;

    public OrderDetail() {
    }

    public OrderDetail(String detailId) {
        this.detailId = detailId;
    }

    public OrderDetail(String detailId, String customerId, String cooperateId, String dispatchNumber, String dispatchCreatTime, String driversID, String sPdtgEmplname, String sPdtgEmplname2, String suicherenyuanID, String suicherenyuanID2, String sPdtgEmplname3, String sPdtgVehicleno, String countPieces, int lPdtgBatch, String ordered, String orderId, String waveKey, String lpn, String mtype, String uom, String detailStatus, String status, java.util.Date addTime, java.util.Date editTime) {
        this.detailId = detailId;
        this.customerId = customerId;
        this.cooperateId = cooperateId;
        this.dispatchNumber = dispatchNumber;
        this.dispatchCreatTime = dispatchCreatTime;
        this.driversID = driversID;
        this.sPdtgEmplname = sPdtgEmplname;
        this.sPdtgEmplname2 = sPdtgEmplname2;
        this.suicherenyuanID = suicherenyuanID;
        this.suicherenyuanID2 = suicherenyuanID2;
        this.sPdtgEmplname3 = sPdtgEmplname3;
        this.sPdtgVehicleno = sPdtgVehicleno;
        this.countPieces = countPieces;
        this.lPdtgBatch = lPdtgBatch;
        this.ordered = ordered;
        this.orderId = orderId;
        this.waveKey = waveKey;
        this.lpn = lpn;
        this.mtype = mtype;
        this.uom = uom;
        this.detailStatus = detailStatus;
        this.status = status;
        this.addTime = addTime;
        this.editTime = editTime;
    }

    public String getDetailId() {
        return detailId;
    }

    public void setDetailId(String detailId) {
        this.detailId = detailId;
    }

    /** Not-null value. */
    public String getCustomerId() {
        return customerId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /** Not-null value. */
    public String getCooperateId() {
        return cooperateId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCooperateId(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    /** Not-null value. */
    public String getDispatchNumber() {
        return dispatchNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDispatchNumber(String dispatchNumber) {
        this.dispatchNumber = dispatchNumber;
    }

    /** Not-null value. */
    public String getDispatchCreatTime() {
        return dispatchCreatTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDispatchCreatTime(String dispatchCreatTime) {
        this.dispatchCreatTime = dispatchCreatTime;
    }

    /** Not-null value. */
    public String getDriversID() {
        return driversID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDriversID(String driversID) {
        this.driversID = driversID;
    }

    /** Not-null value. */
    public String getSPdtgEmplname() {
        return sPdtgEmplname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSPdtgEmplname(String sPdtgEmplname) {
        this.sPdtgEmplname = sPdtgEmplname;
    }

    /** Not-null value. */
    public String getSPdtgEmplname2() {
        return sPdtgEmplname2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSPdtgEmplname2(String sPdtgEmplname2) {
        this.sPdtgEmplname2 = sPdtgEmplname2;
    }

    /** Not-null value. */
    public String getSuicherenyuanID() {
        return suicherenyuanID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSuicherenyuanID(String suicherenyuanID) {
        this.suicherenyuanID = suicherenyuanID;
    }

    /** Not-null value. */
    public String getSuicherenyuanID2() {
        return suicherenyuanID2;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSuicherenyuanID2(String suicherenyuanID2) {
        this.suicherenyuanID2 = suicherenyuanID2;
    }

    /** Not-null value. */
    public String getSPdtgEmplname3() {
        return sPdtgEmplname3;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSPdtgEmplname3(String sPdtgEmplname3) {
        this.sPdtgEmplname3 = sPdtgEmplname3;
    }

    /** Not-null value. */
    public String getSPdtgVehicleno() {
        return sPdtgVehicleno;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSPdtgVehicleno(String sPdtgVehicleno) {
        this.sPdtgVehicleno = sPdtgVehicleno;
    }

    /** Not-null value. */
    public String getCountPieces() {
        return countPieces;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCountPieces(String countPieces) {
        this.countPieces = countPieces;
    }

    public int getLPdtgBatch() {
        return lPdtgBatch;
    }

    public void setLPdtgBatch(int lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public String getOrdered() {
        return ordered;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrdered(String ordered) {
        this.ordered = ordered;
    }

    /** Not-null value. */
    public String getOrderId() {
        return orderId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /** Not-null value. */
    public String getWaveKey() {
        return waveKey;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWaveKey(String waveKey) {
        this.waveKey = waveKey;
    }

    /** Not-null value. */
    public String getLpn() {
        return lpn;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLpn(String lpn) {
        this.lpn = lpn;
    }

    /** Not-null value. */
    public String getMtype() {
        return mtype;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMtype(String mtype) {
        this.mtype = mtype;
    }

    /** Not-null value. */
    public String getUom() {
        return uom;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUom(String uom) {
        this.uom = uom;
    }

    /** Not-null value. */
    public String getDetailStatus() {
        return detailStatus;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDetailStatus(String detailStatus) {
        this.detailStatus = detailStatus;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** Not-null value. */
    public java.util.Date getAddTime() {
        return addTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddTime(java.util.Date addTime) {
        this.addTime = addTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
