package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECYCLE_INPUT.
 */
public class RecycleInput {

    private Long id;
    private int recycleNum;
    /** Not-null value. */
    private java.util.Date recycleTime;
    private java.util.Date editTime;

    public RecycleInput() {
    }

    public RecycleInput(Long id) {
        this.id = id;
    }

    public RecycleInput(Long id, int recycleNum, java.util.Date recycleTime, java.util.Date editTime) {
        this.id = id;
        this.recycleNum = recycleNum;
        this.recycleTime = recycleTime;
        this.editTime = editTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getRecycleNum() {
        return recycleNum;
    }

    public void setRecycleNum(int recycleNum) {
        this.recycleNum = recycleNum;
    }

    /** Not-null value. */
    public java.util.Date getRecycleTime() {
        return recycleTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecycleTime(java.util.Date recycleTime) {
        this.recycleTime = recycleTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
