package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECYCLE_INPUT.
 */
public class RecycleInput {

    private Long id;
    /** Not-null value. */
    private String orderBatchId;
    /** Not-null value. */
    private String cooperateId;
    private int lPdtgBatch;
    /** Not-null value. */
    private String driversID;
    private int recycleNum;
    private long recycleType;
    /** Not-null value. */
    private String recycleTypeValue;
    /** Not-null value. */
    private String status;
    /** Not-null value. */
    private java.util.Date recycleTime;
    private java.util.Date editTime;

    public RecycleInput() {
    }

    public RecycleInput(Long id) {
        this.id = id;
    }

    public RecycleInput(Long id, String orderBatchId, String cooperateId, int lPdtgBatch, String driversID, int recycleNum, long recycleType, String recycleTypeValue, String status, java.util.Date recycleTime, java.util.Date editTime) {
        this.id = id;
        this.orderBatchId = orderBatchId;
        this.cooperateId = cooperateId;
        this.lPdtgBatch = lPdtgBatch;
        this.driversID = driversID;
        this.recycleNum = recycleNum;
        this.recycleType = recycleType;
        this.recycleTypeValue = recycleTypeValue;
        this.status = status;
        this.recycleTime = recycleTime;
        this.editTime = editTime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getOrderBatchId() {
        return orderBatchId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOrderBatchId(String orderBatchId) {
        this.orderBatchId = orderBatchId;
    }

    /** Not-null value. */
    public String getCooperateId() {
        return cooperateId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCooperateId(String cooperateId) {
        this.cooperateId = cooperateId;
    }

    public int getLPdtgBatch() {
        return lPdtgBatch;
    }

    public void setLPdtgBatch(int lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public String getDriversID() {
        return driversID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDriversID(String driversID) {
        this.driversID = driversID;
    }

    public int getRecycleNum() {
        return recycleNum;
    }

    public void setRecycleNum(int recycleNum) {
        this.recycleNum = recycleNum;
    }

    public long getRecycleType() {
        return recycleType;
    }

    public void setRecycleType(long recycleType) {
        this.recycleType = recycleType;
    }

    /** Not-null value. */
    public String getRecycleTypeValue() {
        return recycleTypeValue;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecycleTypeValue(String recycleTypeValue) {
        this.recycleTypeValue = recycleTypeValue;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** Not-null value. */
    public java.util.Date getRecycleTime() {
        return recycleTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecycleTime(java.util.Date recycleTime) {
        this.recycleTime = recycleTime;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

}
