package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RECYCLE_SCAN.
 */
public class RecycleScan {

    private Long id;
    private int lPdtgBatch;
    /** Not-null value. */
    private java.util.Date recycleScanTime;
    /** Not-null value. */
    private String scanCode;
    /** Not-null value. */
    private String status;
    private java.util.Date editTime;
    /** Not-null value. */
    private String userName;

    public RecycleScan() {
    }

    public RecycleScan(Long id) {
        this.id = id;
    }

    public RecycleScan(Long id, int lPdtgBatch, java.util.Date recycleScanTime, String scanCode, String status, java.util.Date editTime, String userName) {
        this.id = id;
        this.lPdtgBatch = lPdtgBatch;
        this.recycleScanTime = recycleScanTime;
        this.scanCode = scanCode;
        this.status = status;
        this.editTime = editTime;
        this.userName = userName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getLPdtgBatch() {
        return lPdtgBatch;
    }

    public void setLPdtgBatch(int lPdtgBatch) {
        this.lPdtgBatch = lPdtgBatch;
    }

    /** Not-null value. */
    public java.util.Date getRecycleScanTime() {
        return recycleScanTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRecycleScanTime(java.util.Date recycleScanTime) {
        this.recycleScanTime = recycleScanTime;
    }

    /** Not-null value. */
    public String getScanCode() {
        return scanCode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScanCode(String scanCode) {
        this.scanCode = scanCode;
    }

    /** Not-null value. */
    public String getStatus() {
        return status;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getEditTime() {
        return editTime;
    }

    public void setEditTime(java.util.Date editTime) {
        this.editTime = editTime;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

}
