package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYS_DIC.
 */
public class SysDic {

    private Long id;
    /** Not-null value. */
    private String myName;
    private String myState;
    private String note;

    public SysDic() {
    }

    public SysDic(Long id) {
        this.id = id;
    }

    public SysDic(Long id, String myName, String myState, String note) {
        this.id = id;
        this.myName = myName;
        this.myState = myState;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMyName() {
        return myName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMyName(String myName) {
        this.myName = myName;
    }

    public String getMyState() {
        return myState;
    }

    public void setMyState(String myState) {
        this.myState = myState;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
