package com.huaren.logistics.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SYS_DIC_VALUE.
 */
public class SysDicValue {

    private Long id;
    /** Not-null value. */
    private String myDisplayValue;
    private int dicId;
    /** Not-null value. */
    private String myName;
    private String note;

    public SysDicValue() {
    }

    public SysDicValue(Long id) {
        this.id = id;
    }

    public SysDicValue(Long id, String myDisplayValue, int dicId, String myName, String note) {
        this.id = id;
        this.myDisplayValue = myDisplayValue;
        this.dicId = dicId;
        this.myName = myName;
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMyDisplayValue() {
        return myDisplayValue;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMyDisplayValue(String myDisplayValue) {
        this.myDisplayValue = myDisplayValue;
    }

    public int getDicId() {
        return dicId;
    }

    public void setDicId(int dicId) {
        this.dicId = dicId;
    }

    /** Not-null value. */
    public String getMyName() {
        return myName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMyName(String myName) {
        this.myName = myName;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

}
